### ISSUE TITLE
Mejora de respuestas al usuario

### ISSUE THREAD

**Issue by rafatorrealba** [rafatorrealba/functionGoogle#1]
Modificar respuestas de a función al usuario: 

a.- ¡Felicidades! La garantía número xxxx está ACTIVA ¿te gustaría planificar una cita para ser atendido por nuestro personal calificado?
b.- ¡Felicidades! La garantía número xxxx está ACTIVA y vence hoy, ¿te gustaría planificar una cita para ser atendido por nuestro personal calificado?
c.- ¡Lo siento! La garantía número XXXX está INACTIVA. ¿te gustaría planificar una cita para ser atendido por nuestro personal calificado?
Según el feedback hay que agregar *felicidades* y *lo siento* a las respuestas del bot. (edited)

**Comment by ubiot-alejandro** [comment]
Mensajes actualizados. Función desplegada.
